### ISSUE TITLE
esm_master get-foci-default -c fails with latest develop and release

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_parser#41]
The following error occurs both with the latest develop and release:

```bash
glogin8:~/esm/esm_parser $ esm_master get-foci-default -c
************************************************************************************
Message found for package esm_tools version 5.0.12:

"ESM Tools version 5.0.5 allows for the generation of hosing files in AWI-ESM-2.1 and AWI-ESM-2.2
To use that, you still need to install a plugin. Please run:

$ pip install --user gfw_creator"

Upgrade this package by typing:              esm_versions upgrade esm_tools
Upgrade all packages by typing:              esm_versions upgrade
************************************************************************************
Traceback (most recent call last):
  File "/home/shkifmsw/.local/bin/esm_master", line 10, in <module>
    sys.exit(main())
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/esm_master.py", line 36, in main_flow
    complete_setup = SimulationSetup(user_config=user_config)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/sim_objects.py", line 31, in __init__
    self.get_total_config_from_user_config(user_config)
  File "/home/shkifmsw/esm/esm_runscripts/esm_runscripts/sim_objects.py", line 150, in get_total_config_from_user_config
    user_config)
  File "/home/shkifmsw/esm/esm_parser/esm_parser/esm_parser.py", line 2575, in __init__
    self._config_init(user_config)
  File "/home/shkifmsw/esm/esm_parser/esm_parser/esm_parser.py", line 2758, in _config_init
    key_path=[], verbose=self.config['general']['verbose'])
KeyError: 'verbose'
```
A workaround is to replace the line
```python
self.config = dict_overwrite(sender=user_config, receiver=self.config,
            key_path=[], verbose=self.config['general']['verbose'])
```
with
```python
self.config = dict_overwrite(sender=user_config, receiver=self.config,
            key_path=[], verbose=self.config['general'].get('verbose',False))
```
in `esm_parser/esm_parser.py`. Output of `esm_versions check`
```bash
glogin8:~/esm/esm_parser $ esm_versions check
+---------------------+-----------+---------------------------------------------------+-------------------------+----------------------+
| package_name        | version   | file                                              | branch                  | tags                 |
|---------------------+-----------+---------------------------------------------------+-------------------------+----------------------|
| esm_calendar        | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                      |
| esm_database        | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                      |
| esm_environment     | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                      |
| esm_master          | 5.0.2     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                      |
| esm_motd            | 5.0.2     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                      |
| esm_parser          | 5.0.8     | /home/shkifmsw/esm/esm_parser                     | develop                 | v5.0.8-18-gbbb6bb2   |
| esm_plugin_manager  | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                      |
| esm_profile         | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                      |
| esm_rcfile          | 5.0.0     | /home/shkifmsw/esm/esm_rcfile                     | develop                 | v5.0.0-3-gc1d2efe    |
| esm_runscripts      | 5.0.16    | /home/shkifmsw/esm/esm_runscripts                 | develop                 | v5.0.16-50-g08189dd  |
| esm_tools           | 5.0.12    | /home/shkifmsw/esm/esm_tools                      | feature/fix_test_script | v5.0.12-126-gcadb230 |
| esm_version_checker | 5.1.2     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                      |
+---------------------+-----------+---------------------------------------------------+-------------------------+----------------------+
```

**Comment by seb-wahl** [comment]
Since it relates to changes that @denizural recently did, I assign it to hi :-)

**Comment by denizural** [comment]
Hi @seb-wahl, I fixed that error (I hope) thanks to @JanStreffing , who first noticed that. Could you please have a look at
https://github.com/esm-tools/esm_parser/pull/40

I actually found another bug in the `esm_environment` just now. It is here: https://github.com/esm-tools/esm_environment/pull/9

My current settings are like this and I can get models:

```
+---------------------+-----------+-----------------------------+--------------------------+
| package_name        | version   | branch                      | tags                     |
|---------------------+-----------+-----------------------------+--------------------------|
| esm_calendar        | 5.0.0     | release                     | v5.0.0                   |
| esm_database        | 5.0.0     |                             |                          |
| esm_environment     | 5.0.0     | hotfix/forgotten_sys_module | v5.0.0-19-gdc87802-dirty |
| esm_master          | 5.0.7     | develop                     | v5.0.7-17-g398fa5b       |
| esm_motd            | 5.0.1     | release                     | v5.0.1                   |
| esm_parser          | 5.0.8     | hotfix/verbose_bug          | v5.0.8-2-gef67b8d        |
| esm_plugin_manager  | 5.0.1     | release                     | v5.0.1-1-g42544c3        |
| esm_profile         | 5.0.0     |                             |                          |
| esm_rcfile          | 5.0.0     | develop                     | v5.0.0-3-gc1d2efe        |
| esm_runscripts      | 5.0.17    | hist_fixed                  | v5.0.17-76-gcb36307      |
| esm_tools           | 5.0.17    | hist_fixed                  | v5.0.17-61-g3c2720e      |
| esm_version_checker | 5.1.2     | release                     | v5.1.2-1-ge6066ba        |
+---------------------+-----------+-----------------------------+--------------------------+
```

**Comment by denizural** [comment]
I merged the hotfix and the bug fix for the develop from `esm_environment`. It seems to be working so I am closing this issue.
